// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: proto/orderService.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemsOfOrderByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsOfOrderByIdRequest) Reset() {
	*x = GetItemsOfOrderByIdRequest{}
	mi := &file_proto_orderService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsOfOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsOfOrderByIdRequest) ProtoMessage() {}

func (x *GetItemsOfOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsOfOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetItemsOfOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemsOfOrderByIdRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetItemsOfOrderByIdResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ListOfProductsId []int32                `protobuf:"varint,1,rep,packed,name=listOfProductsId,proto3" json:"listOfProductsId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetItemsOfOrderByIdResponse) Reset() {
	*x = GetItemsOfOrderByIdResponse{}
	mi := &file_proto_orderService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsOfOrderByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsOfOrderByIdResponse) ProtoMessage() {}

func (x *GetItemsOfOrderByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsOfOrderByIdResponse.ProtoReflect.Descriptor instead.
func (*GetItemsOfOrderByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemsOfOrderByIdResponse) GetListOfProductsId() []int32 {
	if x != nil {
		return x.ListOfProductsId
	}
	return nil
}

type GetOrderByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByUserIdRequest) Reset() {
	*x = GetOrderByUserIdRequest{}
	mi := &file_proto_orderService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByUserIdRequest) ProtoMessage() {}

func (x *GetOrderByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderByUserIdRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOrderByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByUserIdResponse) Reset() {
	*x = GetOrderByUserIdResponse{}
	mi := &file_proto_orderService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByUserIdResponse) ProtoMessage() {}

func (x *GetOrderByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderByUserIdResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CartId               int32                  `protobuf:"varint,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	TypeOfTransportation string                 `protobuf:"bytes,3,opt,name=TypeOfTransportation,proto3" json:"TypeOfTransportation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_orderService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateOrderRequest) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *CreateOrderRequest) GetTypeOfTransportation() string {
	if x != nil {
		return x.TypeOfTransportation
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_orderService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderResponse) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CartId        int32                  `protobuf:"varint,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	CreateAt      int32                  `protobuf:"varint,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	DeliveredAt   int32                  `protobuf:"varint,4,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	TransportType string                 `protobuf:"bytes,5,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"`
	UserId        int32                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_orderService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_orderService_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *Order) GetCreateAt() int32 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Order) GetDeliveredAt() int32 {
	if x != nil {
		return x.DeliveredAt
	}
	return 0
}

func (x *Order) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *Order) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_orderService_proto protoreflect.FileDescriptor

const file_proto_orderService_proto_rawDesc = "" +
	"\n" +
	"\x18proto/orderService.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\x1aGetItemsOfOrderByIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"I\n" +
	"\x1bGetItemsOfOrderByIdResponse\x12*\n" +
	"\x10listOfProductsId\x18\x01 \x03(\x05R\x10listOfProductsId\"2\n" +
	"\x17GetOrderByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\">\n" +
	"\x18GetOrderByUserIdResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.proto.OrderR\x05order\"q\n" +
	"\x12CreateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\acart_id\x18\x02 \x01(\x05R\x06cartId\x122\n" +
	"\x14TypeOfTransportation\x18\x03 \x01(\tR\x14TypeOfTransportation\"T\n" +
	"\x13CreateOrderResponse\x12=\n" +
	"\fdelivered_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\"\xb0\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\acart_id\x18\x02 \x01(\x05R\x06cartId\x12\x1b\n" +
	"\tcreate_at\x18\x03 \x01(\x05R\bcreateAt\x12!\n" +
	"\fdelivered_at\x18\x04 \x01(\x05R\vdeliveredAt\x12%\n" +
	"\x0etransport_type\x18\x05 \x01(\tR\rtransportType\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x05R\x06userId2\x8d\x02\n" +
	"\fOrderService\x12F\n" +
	"\vCreateOrder\x12\x19.proto.CreateOrderRequest\x1a\x1a.proto.CreateOrderResponse\"\x00\x12U\n" +
	"\x10GetOrderByUserId\x12\x1e.proto.GetOrderByUserIdRequest\x1a\x1f.proto.GetOrderByUserIdResponse\"\x00\x12^\n" +
	"\x13GetItemsOfOrderById\x12!.proto.GetItemsOfOrderByIdRequest\x1a\".proto.GetItemsOfOrderByIdResponse\"\x00B\x11Z\x0f./proto;orderpbb\x06proto3"

var (
	file_proto_orderService_proto_rawDescOnce sync.Once
	file_proto_orderService_proto_rawDescData []byte
)

func file_proto_orderService_proto_rawDescGZIP() []byte {
	file_proto_orderService_proto_rawDescOnce.Do(func() {
		file_proto_orderService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderService_proto_rawDesc), len(file_proto_orderService_proto_rawDesc)))
	})
	return file_proto_orderService_proto_rawDescData
}

var file_proto_orderService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orderService_proto_goTypes = []any{
	(*GetItemsOfOrderByIdRequest)(nil),  // 0: proto.GetItemsOfOrderByIdRequest
	(*GetItemsOfOrderByIdResponse)(nil), // 1: proto.GetItemsOfOrderByIdResponse
	(*GetOrderByUserIdRequest)(nil),     // 2: proto.GetOrderByUserIdRequest
	(*GetOrderByUserIdResponse)(nil),    // 3: proto.GetOrderByUserIdResponse
	(*CreateOrderRequest)(nil),          // 4: proto.CreateOrderRequest
	(*CreateOrderResponse)(nil),         // 5: proto.CreateOrderResponse
	(*Order)(nil),                       // 6: proto.Order
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
}
var file_proto_orderService_proto_depIdxs = []int32{
	6, // 0: proto.GetOrderByUserIdResponse.order:type_name -> proto.Order
	7, // 1: proto.CreateOrderResponse.delivered_at:type_name -> google.protobuf.Timestamp
	4, // 2: proto.OrderService.CreateOrder:input_type -> proto.CreateOrderRequest
	2, // 3: proto.OrderService.GetOrderByUserId:input_type -> proto.GetOrderByUserIdRequest
	0, // 4: proto.OrderService.GetItemsOfOrderById:input_type -> proto.GetItemsOfOrderByIdRequest
	5, // 5: proto.OrderService.CreateOrder:output_type -> proto.CreateOrderResponse
	3, // 6: proto.OrderService.GetOrderByUserId:output_type -> proto.GetOrderByUserIdResponse
	1, // 7: proto.OrderService.GetItemsOfOrderById:output_type -> proto.GetItemsOfOrderByIdResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_orderService_proto_init() }
func file_proto_orderService_proto_init() {
	if File_proto_orderService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderService_proto_rawDesc), len(file_proto_orderService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderService_proto_goTypes,
		DependencyIndexes: file_proto_orderService_proto_depIdxs,
		MessageInfos:      file_proto_orderService_proto_msgTypes,
	}.Build()
	File_proto_orderService_proto = out.File
	file_proto_orderService_proto_goTypes = nil
	file_proto_orderService_proto_depIdxs = nil
}
